
package WebServiceClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceHello", targetNamespace = "http://WebService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceHello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://WebService/", className = "WebServiceClient.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://WebService/", className = "WebServiceClient.GetNameResponse")
    @Action(input = "http://WebService/ServiceHello/getNameRequest", output = "http://WebService/ServiceHello/getNameResponse")
    public String getName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
